name: deploy.yml

on:
  workflow_call: 
    inputs: 
      stageName:
        required: true
        type: string
      tagName:
        type: string

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.stageName }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        if: inputs.tagName == ''

      - name: Checkout Tag
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        if: inputs.tagName != ''
        with:
          ref: ${{ inputs.tagName }}

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          terraform_version: 1.14.9

      - name: Terraform init
        run: make init
        working-directory: terraform/envs/${{ inputs.stageName }}
        env:
          BACKEND_S3_BUCKET: ${{ secrets.BACKEND_S3_BUCKET }}
          BACKEND_S3_KEY: ${{ secrets.BACKEND_S3_KEY }}
          BACKEND_REGION: ${{ vars.AWS_REGION }}

      - name: Terraform apply
        run: make apply
        working-directory: terraform/envs/${{ inputs.stageName }}
        env:
          TF_VAR_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_SYSTEM_NAME: ${{ vars.SYSTEM_NAME }}
          TF_VAR_SLACK_INCOMING_WEBHOOK_ERROR_NOTIFIER_01: ${{ secrets.SLACK_INCOMING_WEBHOOK_ERROR_NOTIFIER_01 }}
