on:
  push:
    branches:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - run: |
          pip install poetry
          poetry install
      - run: make lint
