name: release-prd.yml
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  release-production:
    name: Release Production
    uses: ./.github/workflows/deploy.yml
    with: 
      stageName: prd
      tagName: ${{ github.ref }}
    secrets: inherit
