on:
  push:
    branches:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - run: |
          pip install poetry
          poetry install
      - run: make compose-up
      - run: make test-unit
